# Generated by Django 3.1.7 on 2022-01-15 17:43

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default=None, upload_to=recipe.models.user_directory_path, verbose_name='Recipe pics'),
            preserve_default=False,
        ),
    ]
