# Generated by Django 3.1.7 on 2022-01-15 17:52

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20220115_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=recipe.models.user_directory_path, verbose_name='Recipe pics'),
        ),
    ]
